
[Constants]
MainEdiz=3
MainWRHS=3
MainPlant=21
MainMVP=39
MainCount=2
MainStat=5
OpenAllFormMaximized=0


[Config]
#
#  CheckBDEConfig - проверяет конфигурацию BDE. Если параметр=0
#    тогда проверяется наличие алиаса. Если алиаса RMP нет, то
#    он создается по пути DatabaseName.
#    1 - Конфигурация берется из BDE по умолчанию
#

CheckBDEConfig=0
DatabaseName=D:\Projects\Archangelsk\RMP\VM\Exe70\RMP_NEW.GDB
#D:\Проекты\RMP\Exe70\RMP.GDB
#10.11.0.100:d:\sys\PetrSU\Base\Rmp.gdb
#E:\Проекты\RMP\Base\RMP.GDB
#Forest:D:projects\ASUP\MES\Archangelsk\Rmp.gdb
#D:\Проекты\RMP\Base\base.GDB
#forest:D:\Projects\ASUP\MES\Archangelsk\base1.GDB
#forest:D:\Projects\ASUP\MES\Archangelsk\base.GDB
#D:\Проекты\RMP\031205\Exe\RMP.GDB
#forest:D:\Projects\ASUP\MES\Archangelsk\RMP.GDB
#@D:\Проекты\RMP\031205\Exe\RMP.GDB
#forest:d:\Project\ASUP\MES\Archangelsk\RMP.GDB
# 10.11.0.100:d:\sys\PetrSU\Base\Rmp.gdb
# [\\10.11.0.100\Sys\PetrSU\Base\RMP.GDB]
CurPlanPeriod=150
CurFactPeriod=150
WorkDate=02.10.2004
DateFrom=02.10.2004
DateTo=02.10.2004
Enterprise=ОАО "ЦБК"
Service=РМП ЦБК
Mechanic=Иванов В.А.
Manager=Петров В.У.
Economist=Сидоров Ю.А.
OKYD=0335018
OKPO=00279100
HOST=smtp.mail.ru
PORT=465
POST_USERNAME=]_Z`e\mЏ„‰ЌT™™
POST_PASSWORD=ЏЌЊ“њЋ’”ZU
ADRESS_FROM=]_Z`e\mЏ„‰ЌT™™
Recipient=svl@karelia.ru

[Calculation]
# ID статьи затрат для расчета полной себестоимости заказа.
# Для внутренних подразделений она считается по цеховой себестоимости.
# Для сторонних накручиваются плановые накопления, общезаводские расходы и НДС.
CalcIDForInternal=6
CalcIDForExternal=11
[Sprav]
CodeChrt=ГИД.9877890
[Journal]
DateOut=14.04.2006        
