#
#  Стартовый программный файл для АСУ РМП
#

[Constants]
MainEdiz=3
MainWRHS=3
MainPlant=23
MainMVP=4
MainCount=1
MainStat=5
OpenAllFormMaximized=1


[Config]
#
#  CheckBDEConfig - проверяет конфигурацию BDE. Если параметр=0
#    тогда проверяется наличие алиаса. Если алиаса RMP нет, то
#    он создается по пути DatabaseName.
#    1 - Конфигурация берется из BDE по умолчанию
#

CheckBDEConfig=0
DatabaseName=10.11.0.100:d:\sys\PetrSU\Base\Rmp.gdb
# [10.11.0.100:d:\Sys\PetrSU\Base\RMP.gdb]
CurPlantPeriod=51
CurFactPeriod=112
WorkDate=20.10.04
DateFrom=01.10.04
DateTo=30.10.04
CURPLANPERIOD=112
Enterprise=ОАО "Архангельский ЦБК"
Service=РМП АЦБК
Mechanic=Андриевский Ю.И.
Manager=Торопов Ф.А.
Economist=Шмаков Ю.А.

[Calculation]
CalcIDForInternal=6
CalcIDForExternal=12

[Journal]
DateOut=31.01.2006
